export const guestList = [
  ["Ken", "Terri"],
  ["Jordan", "Harlie"],
  ["Letty"],
  ["Brandy"],
  ["Thomas"],
  ["Liam"],
  ["Alex"],
  ["Enzo"],
  ["Ezequiel", "Shayna"],
  ["Javier", "PLUSONE"],
  ["Johnny", "Alyssa"],
  ["Daniel", "Daisy"],
  ["Hunter"],
  ["Zach"],
  ["Tyler", "PLUSONE"],
  ["Jessica", "PLUSONE"],
  ["Barbara", "PLUSONE"],
  ["Jim", "PLUSONE"],
  ["Evelynn", "PLUSONE"],
  ["Elia", "Ofe"],
  ["Greg", "Frida"],
  ["John", "PLUSONE"],
  ["Kathleen", "PLUSONE"],
  ["Cheri", "PLUSONE"],
  ["Illiana", "PLUSONE"],
  ["Dulce", "PLUSONE"],
  ["Lisa", "PLUSONE"],
  ["Teri", "PLUSONE"],
  ["Sydney", "PLUSONE"],
  ["Taylor", "PLUSONE"],
  ["Josh", "PLUSONE"],
  ["Hannah", "Isaac"],
  ["David", "Vickie"],
  ["Ryan", "PLUSONE"],
  ["Lauren", "Cody"],
  ["Tim", "Denise"],
  ["Mike", "Judy"],
  ["Chuck", "Ricky"],
  ["Granny", "Poppy"],
];

export const desiredInvitationOrder = [
  "Ken & Terri",
  "Jordan & Harlie",
  "Letty",
  "Brandy",
  "Thomas",
  "Liam",
  "Alex",
  "Enzo",
  "Ezequiel & Shayna",
  "Javier + Guest",
  "Johnny & Alyssa",
  "Daniel & Daisy",
  "Hunter",
  "Zach",
  "Tyler + Guest",
  "Jessica + Guest",
  "Barbara + Guest",
  "Jim + Guest",
  "Evelynn + Guest",
  "Elia & Ofe",
  "Greg & Frida",
  "John + Guest",
  "Kathleen + Guest",
  "Cheri + Guest",
  "Illiana + Guest",
  "Dulce + Guest",
  "Lisa + Guest",
  "Teri + Guest",
  "Sydney + Guest",
  "Taylor + Guest",
  "Josh + Guest",
  "Hannah & Isaac",
  "David & Vickie",
  "Ryan + Guest",
  "Lauren & Cody",
  "Tim & Denise",
  "Mike & Judy",
  "Chuck & Ricky",
  "Granny & Poppy",
];
