export const guestList = [
  ["Ken", "Terri"],
  ["Jordan", "Harlie"],
  ["Letty"],
  ["Brandy"],
  ["Thomas"],
  ["Liam"],
  ["Alex"],
  ["Ezequiel", "Shayna"],
  ["Javier"],
  ["Johnny", "Alyssa"],
  ["Daniel", "Daisy"],
  ["Hunter"],
  ["Zach"],
  ["Tyler", "PLUSONE"],
  ["Jessica", "PLUSONE"],
  ["Barbara", "PLUSONE"],
  ["Jim", "PLUSONE"],
  ["Evelynn", "PLUSONE"],
  ["Elia", "Ofe"],
  ["John", "Johns GF"],
  ["Kathleen", "PLUSONE"],
  ["Dulce", "PLUSONE"],
  ["Lisa"],
  ["Teri"],
  ["Sydney"],
  ["Taylor"],
  ["Josh", "Nicole"],
  ["Hannah", "Isaac"],
  ["David", "Vickie"],
  ["Ryan", "Gracie"],
  ["Lauren", "Cody"],
  ["Tim", "Denise"],
  ["Mike", "Judy"],
  ["Chuck", "Ricky"],
  ["Granny", "Poppy"],
  ["Kami"],
];
