packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: 19.2.3
  react-dom: 19.2.3
  clsx: 2.1.1
  lucide-react: 0.540.0
  drizzle-kit: 0.31.4
  drizzle-orm: 0.44.5
  postgres: 3.4.7
  postcss: 8.5.6
  postcss-mixins: 12.1.2
  "@tailwindcss/postcss": 4.1.17
  tailwindcss: 4.1.17
  tw-animate-css: 1.4.0
  "@types/node": 24.10.0
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  typescript: 5.9.3
  eslint: 9.39.1
  playwright: 1.56.1
  vitest: 4.0.9
  "@vitest/coverage-v8": 4.0.9
  dotenv: 17.2.2
  "@vitest/browser": 4.0.9
  "@hookform/resolvers": 5.2.2
  "@radix-ui/react-accordion": 1.2.2
  "@radix-ui/react-alert-dialog": 1.1.15
  "@radix-ui/react-aspect-ratio": 1.1.1
  "@radix-ui/react-avatar": 1.1.2
  "@radix-ui/react-checkbox": 1.3.3
  "@radix-ui/react-collapsible": 1.1.2
  "@radix-ui/react-context-menu": 2.2.4
  "@radix-ui/react-dialog": 1.1.15
  "@radix-ui/react-dropdown-menu": 2.1.16
  "@radix-ui/react-hover-card": 1.1.4
  "@radix-ui/react-label": 2.1.7
  "@radix-ui/react-menubar": 1.1.4
  "@radix-ui/react-navigation-menu": 1.2.14
  "@radix-ui/react-popover": 1.1.15
  "@radix-ui/react-progress": 1.1.1
  "@radix-ui/react-radio-group": 1.2.2
  "@radix-ui/react-scroll-area": 1.2.2
  "@radix-ui/react-select": 2.2.6
  "@radix-ui/react-separator": 1.1.1
  "@radix-ui/react-slider": 1.2.2
  "@radix-ui/react-slot": 1.2.3
  "@radix-ui/react-switch": 1.1.2
  "@radix-ui/react-tabs": 1.1.2
  "@radix-ui/react-toast": 1.2.4
  "@radix-ui/react-toggle": 1.1.1
  "@radix-ui/react-toggle-group": 1.1.1
  "@radix-ui/react-tooltip": 1.1.6
  "@reduxjs/toolkit": 2.11.2
  react-redux: 9.2.0
  class-variance-authority: 0.7.1
  cmdk: 1.0.4
  date-fns: 4.1.0
  embla-carousel-react: 8.5.1
  input-otp: 1.4.1
  next-themes: 0.4.6
  react-day-picker: 9.11.1
  react-hook-form: 7.65.0
  react-resizable-panels: 2.1.7
  recharts: 2.15.4
  sonner: 2.0.7
  tailwind-merge: 3.3.1
  tailwindcss-animate: 1.0.7
  vaul: 1.1.2
  zod: 4.1.12
  gsap: 3.13.0
