-- i ran this on 9/28/2025  directly into the db 
-- via the neondb console, this is just for record keeping

INSERT INTO invitations (name_on_invitation, is_attending, has_plus_one)
VALUES
  ('Ken', false, false),
  ('Terri', false, false),
  ('Jordan', false, false),
  ('Harlie', false, false),
  ('Letty', false, false),
  ('Brandy', false, false),
  ('Thomas', false, false),
  ('Liam', false, false),
  ('Alex', false, false),
  ('Ezequiel', false, false),
  ('Shayna', false, false),
  ('Javier', false, false),
  ('Johnny', false, false),
  ('Alyssa', false, false),
  ('Daniel', false, false),
  ('Daisy', false, false),
  ('Hunter', false, false),
  ('Zach', false, false),
  ('Tyler', false, true),
  ('Jessica', false, true),
  ('Barbara', false, true),
  ('Jim', false, true),
  ('Evelynn', false, true),
  ('Elia', false, false),
  ('Ofe', false, false),
  ('John', false, true),
  ('Kathleen', false, true),
  ('Dulce', false, true),
  ('Lisa', false, false),
  ('Teri', false, false),
  ('Sydney', false, false),
  ('Taylor', false, false),
  ('Josh', false, false),
  ('Nicole', false, false),
  ('Hannah', false, false),
  ('Isaac', false, false),
  ('David', false, false),
  ('Vickie', false, false),
  ('Ryan', false, false),
  ('Lauren', false, false),
  ('Cody', false, false),
  ('Tim', false, false),
  ('Denise', false, false),
  ('Mike', false, false),
  ('Judy', false, false),
  ('Chuck', false, false),
  ('Ricky', false, false),
  ('Granny', false, false),
  ('Poppy', false, false);



INSERT INTO invitation_groups (guest_a, guest_b) VALUES
  ('Ken', 'Terri'),
  ('Jordan', 'Harlie'),
  ('Johnny', 'Alyssa'),
  ('Daniel', 'Daisy'),
  ('Ezequiel', 'Shayna'),
  ('Elia', 'Ofe'),  
  ('Josh', 'Nicole'),
  ('Hannah', 'Isaac'),
  ('David', 'Vickie'),
  ('Lauren', 'Cody'),
  ('Tim', 'Denise'),
  ('Mike', 'Judy'),
  ('Chuck', 'Ricky'),
  ('Granny', 'Poppy');

INSERT INTO invitation_groups (guest_a) VALUES
  ('Letty'),
  ('Brandy'),
  ('Thomas'),
  ('Liam'),
  ('Alex'),
  ('Javier'),
  ('Hunter'),
  ('Zach'),
  ('Tyler'),
  ('Jessica'),
  ('Barbara'),
  ('Jim'),
  ('Evelynn'),
  ('John'),
  ('Kathleen'),
  ('Dulce'),
  ('Lisa'),
  ('Teri'),
  ('Sydney'),
  ('Taylor'),
  ('Ryan');